# Generated by Django 5.2.12 on 2026-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('tournament', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('team_a', models.CharField(max_length=100)),
                ('team_a_short', models.CharField(max_length=10)),
                ('team_b', models.CharField(max_length=100)),
                ('team_b_short', models.CharField(max_length=10)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
